version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_RETENTION_MS: 60000
      KAFKA_CLEANUP_POLICY: delete
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  generator:
    image: generator:0.1
    environment:
      DIMENSIONS: 8
      GEN_POINT: uniform
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OUTPUT_TOPIC: points

  classifier:
    image: classifier:0.1
    environment:
      DIMENSIONS: 8
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      INPUT_TOPIC: points
      OUTPUT_TOPIC: matches

  validator:
    image: validator:0.1
    environment:
      DIMENSIONS: 8
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      INPUT_TOPIC: matches
