global:
  scrape_interval: 10s
  scrape_timeout: 1s

scrape_configs:
  - job_name: classifier
    metrics_path: /metrics
    dns_sd_configs:
    - names:
      - "tasks.classifier"
      type: "A"
      port: 8080
