{
 "title": "Thesis",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Group",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "classifier_group", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "min(sum by(group)(rate(classifier_points_processed_total[1m])))"
    }
   ]
  },
  {
   "title": "Points generated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(generator_points_generated_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Points processed by group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group)(rate(classifier_points_processed_total[1m]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Points processed by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(classifier_points_processed_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Matches found",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(classifier_matches_found_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Matches validated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_matches_total[1m])"
    }
   ]
  },
  {
   "title": "Rules total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "classifier_rules_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Generator heap used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"generator\", area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Classifier heap used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"classifier\", area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}